services:
  demo-app:
    image: demoapp
    build:
      context: .
      dockerfile: DemoApp/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      - ACCEPT_EULA=1
      - MSSQL_USER=SA
      - MSSQL_SA_PASSWORD=SQLConnect1\!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"